[package]
name = "locutus-token-allocation-record"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true }
locutus-stdlib = { workspace = true }
rsa = { workspace = true, features = ["sha2"] }
serde = { workspace = true }
serde_json = { workspace = true }
pico-args = "0.5"

locutus-aft-interface = { path = "../../interfaces" }

[lib]
crate-type = ["cdylib", "rlib"]
