[package]
name = "locutus-token-allocation-record"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true }
locutus-stdlib = { workspace = true }
ed25519-dalek = { workspace = true }
serde = { workspace = true }

locutus-aft-interface = { path = "../../interfaces" }

[lib]
crate-type = ["cdylib"]
