[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["contracts/test-contract", "contracts/freenet-microblogging-web", "contracts/freenet-microblogging-data"]

[profile.dev.package."*"]
opt-level = 3

# [profile.release]
# strip = true
# opt-level = "z"
# lto = true
# codegen-units = 1
# panic = "abort"
