[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["contracts/test_contract"]

[profile.dev.package."*"]
opt-level = 3

[profile.release.package."*"]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
