[package]
name = "locutus-token-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
chrono = { workspace = true }
locutus-stdlib = { workspace = true }
ed25519-dalek = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

locutus-aft-interface = { path = "../../interfaces" }

[dev-dependencies]
arbitrary = "1"
once_cell = "1"
chacha20poly1305 = "0.10"
rand = { version = "0.7", features = ["std"] }
locutus-stdlib = { workspace = true, features = ["testing"] }
locutus-runtime = { path = "../../../../crates/locutus-runtime", version = "0.0.3" }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "fmt"] }

[lib]
crate-type = ["cdylib"]
