[package]
name = "freenet-email-ui"
version = "0.0.1"
edition = "2021"
rust-version = "1.58.0"
resolver = "2"
publish = false

[dependencies]
ed25519-dalek = { workspace = true }
chacha20poly1305 = { workspace = true, features = ["std"] }
chrono = { workspace = true }
dioxus = { version = "0.3" }
locutus-stdlib = { workspace = true, features = ["net"] }
locutus-aft-interface = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

freenet-email-inbox = { path = "../contracts/inbox" }

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_family = "wasm")'.dependencies]
dioxus-web = { version = "0.3" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
dioxus-desktop = { version = "0.3" }
