[package]
name = "freenet-email-ui"
version = "0.0.1"
edition = "2021"
rust-version = "1.58.0"
resolver = "2"
publish = false
default-run = "app"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "get_code_hash"
required-features = ["build-binary"]

[[bin]]
name = "app"

[dependencies]
arc-swap = "1.6"
rand_chacha = "0.3"
chrono = { workspace = true }
crossbeam = "0.8"
dioxus = { version = "0.3" }
futures = "0.3"
locutus-stdlib = { workspace = true, features = ["net"] }
locutus-aft-interface = { workspace = true }
rsa = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { version = "0.1" }
tracing-subscriber = "0.3"
wasm-bindgen = "0.2"
once_cell = "1"

freenet-email-inbox = { path = "../contracts/inbox", features = ["wasmbind"] }
locutus-dev = { path = "../../../crates/locutus-dev", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
dioxus-web = { version = "0.3" }
getrandom = { version = "*", features = ["js"] }
locutus-stdlib = { workspace = true, features = ["net"] }
serde-wasm-bindgen = { version = "0.5" }

[target.'cfg(target_family = "wasm")'.dependencies.web-sys]
version = "0.3"
features = [
  "BinaryType",
  "Blob",
  "console",
  "ErrorEvent",
#   "FileReader",
#   "MessageEvent",
#   "ProgressEvent",
  "WebSocket",
  "Window"
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
dioxus-desktop = { version = "0.3" }

[features]
default = ["ui-testing"]
ui-testing = []
use-node = []
build-binary = ["locutus-dev"]
