[package]
name = "freenet-email-ui"
version = "0.0.1"
edition = "2021"
rust-version = "1.58.0"
resolver = "2"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rand_chacha = "0.3"
chrono = { workspace = true }
crossbeam = "0.8"
dioxus = { version = "0.3" }
locutus-stdlib = { workspace = true, features = ["net"] }
locutus-aft-interface = { workspace = true }
once_cell = { workspace = true }
rsa = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

freenet-email-inbox = { path = "../contracts/inbox", features = ["wasmbind"] }

[target.'cfg(target_family = "wasm")'.dependencies]
dioxus-web = { version = "0.3" }
getrandom = { version = "*", features = ["js"] }
locutus-stdlib = { workspace = true, features = ["net"] }
serde-wasm-bindgen = { version = "0.5" }

[target.'cfg(target_family = "wasm")'.dependencies.web-sys]
version = "0.3"
features = [
  "BinaryType",
  "Blob",
  "console",
  "ErrorEvent",
#   "FileReader",
#   "MessageEvent",
#   "ProgressEvent",
  "WebSocket",
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
dioxus-desktop = { version = "0.3" }
# dioxus-hot-reload = "0.1"

[features]
default = ["ui-testing"]
ui-testing = []
node = []
