[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = true
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served. (Comment this when running trunk serve)
public_url = "./"
# Whether to include hash values in the output file names.
filehash = false
# Whether to inject scripts (and module preloads) into the finalized output.
inject_scripts = false