[package]
name = "freenet-microblogging-controller"
version = "0.0.0"
edition = "2021"
rust-version = "1.58.0"
resolver = "2"
publish = false

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["serde", "alloc"] }
locutus-stdlib = { path = "../../../crates/locutus-stdlib" }
serde = "1"
serde_json = "1"
serde_with = "1"
ed25519-dalek = { version = "1", features = ["serde", "u32_backend"], default-features = false }
byteorder = "1"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
byteorder = "1"
serde = "1"
serde_json = "1"
tar = "0.4"
xz2 = "0.1"
