[package]
name = "locutus-aft-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
chrono = { workspace = true }
locutus-stdlib = { workspace = true }
rsa = { workspace = true }
serde = { workspace = true }
strum = { version = "0.24", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
hex-literal = "0.3.4"
# FIXME: addign rand here pulls rand for transitive deps and gets included in the final wasm32 bin
rand = "*"
