on:
  issues:
    types: [opened, closed]

jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Send message via Matrix
    steps:
    - name: Send message to test channel
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: 'matrix.org'
        token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
        channel: ${{ secrets.MATRIX_ROOM_ID }}
        message: |
          Issue #${{ github.event.issues.issue.id }} ${{ github.event.issues.action }} : [${{ github.event.issues.issue.title }}](${{ github.event.issues.issue.html_url }})
